name: flublade_project
description: Sandbox MMORPG game.
publish_to: 'none'
version: "1.0.0+1"
environment:
  sdk: '>=2.17.0 <3.0.0'
# Project Depedencies
dependencies:
  flutter:
    sdk: flutter
  #System
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  http: ^0.13.5
  web_socket_channel: ^2.4.0
  package_info_plus: ^4.2.0
  #Engine
  flame: ^1.13.1
  flutter_joystick: ^0.0.3
  window_manager: ^0.3.7
  cupertino_icons: ^1.0.2

# Debug Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Packages
flutter:
  assets:
    # Menu
    - assets/images/menu/
    - assets/images/menu/character_creation/
    - assets/images/menu/classes/
    # Skills
    - assets/images/skills/
    - assets/images/skills/passives/
    # Items
    - assets/images/items/
    # NPC
    - assets/images/npc/
    # Tilesets
    - assets/images/tilesets/overworld/
    # Interface
    - assets/images/interface/
    # Classes
    - assets/images/menu/classes/
    # Human
    - assets/images/players/human/body/
    - assets/images/players/human/eyes/0/
    - assets/images/players/human/eyes/1/
    - assets/images/players/human/hair/0/
    - assets/images/players/human/hair/1/
    - assets/images/players/human/mouth/0/
    - assets/images/players/human/mouth/1/
    - assets/images/players/human/skin/0/
    - assets/images/players/human/skin/1/
    # Aghars
    - assets/images/players/aghars/body/
    - assets/images/players/aghars/eyes/0/
    - assets/images/players/aghars/eyes/1/
    - assets/images/players/aghars/hair/0/
    - assets/images/players/aghars/hair/1/
    - assets/images/players/aghars/mouth/0/
    - assets/images/players/aghars/mouth/1/
    - assets/images/players/aghars/skin/0/
    - assets/images/players/aghars/skin/1/
    # Nature
    - assets/images/players/nature/body/
    - assets/images/players/nature/eyes/0/
    - assets/images/players/nature/eyes/1/
    - assets/images/players/nature/hair/0/
    - assets/images/players/nature/hair/1/
    - assets/images/players/nature/mouth/0/
    - assets/images/players/nature/mouth/1/
    - assets/images/players/nature/skin/0/
    - assets/images/players/nature/skin/1/
    # Dytol
    - assets/images/players/dytol/body/
    - assets/images/players/dytol/eyes/0/
    - assets/images/players/dytol/eyes/1/
    - assets/images/players/dytol/hair/0/
    - assets/images/players/dytol/hair/1/
    - assets/images/players/dytol/mouth/0/
    - assets/images/players/dytol/mouth/1/
    - assets/images/players/dytol/skin/0/
    - assets/images/players/dytol/skin/1/
    # Dark
    - assets/images/players/dark/body/
    - assets/images/players/dark/eyes/0/
    - assets/images/players/dark/eyes/1/
    - assets/images/players/dark/hair/0/
    - assets/images/players/dark/hair/1/
    - assets/images/players/dark/mouth/0/
    - assets/images/players/dark/mouth/1/
    - assets/images/players/dark/skin/0/
    - assets/images/players/dark/skin/1/
    # Undead
    - assets/images/players/undead/body/
    - assets/images/players/undead/eyes/0/
    - assets/images/players/undead/eyes/1/
    - assets/images/players/undead/hair/0/
    - assets/images/players/undead/hair/1/
    - assets/images/players/undead/mouth/0/
    - assets/images/players/undead/mouth/1/
    - assets/images/players/undead/skin/0/
    - assets/images/players/undead/skin/1/
    # Monster
      #drauy_monsters
    - assets/images/enemies/
    - assets/images/enemies/infight/
    # locations
      #drauy_location
    - assets/images/locations/drauy_dungeon/
      #prologue
    - assets/images/locations/prologue/
  uses-material-design: true
  fonts:
    - family: PressStart
      fonts:
        - asset: assets/fonts/PressStart-Regular.ttf
          style: italic
    - family: Explora
      fonts:
        - asset: assets/fonts/Explora-Regular.ttf
          style: italic